"""Tier boards: the data layer behind ranking titles into ordered tiers.

One job: read and write `tier_boards`, `tier_categories` and `tier_items`. No
HTTP, no request objects, no image work — routes parse and respond, this module
decides what the database ends up holding.

THE ACCESS RULE, and the reason this module reads the way it does: a board or a
category is NEVER addressed by its integer id from outside. Every public
function here takes a `user_id` from the session plus a client-supplied `uid`,
and resolves the pair against rows the session user owns. Integer ids exist only
inside a single call, after ownership has been established. That is what makes a
cross-tenant reference impossible to even express: there is no request shape that
names somebody else's board, because the only name a request can use is scoped to
the caller. Every UPDATE and DELETE additionally carries the ownership predicate
in its WHERE clause, so a mistake in the resolution step still cannot write
across accounts.

ITEM ADDRESSING. Items have no uid column of their own. Their identity within a
board is the triple (media, match_source, match_id), which is also their UNIQUE
constraint, so the composite key "{media}:{match_source}:{match_id}" is what a
client refers to an item by. Like a uid it survives a restore into a database
whose rowids came out different, and like a uid it is meaningless outside the
board it was resolved against.

WHAT A SAVE MAY DO. save_layout() is targeted upserts and updates inside one
transaction, never a wipe-and-reinsert: reinserting loses whatever a second tab
wrote in between and churns the id space for no reason. A stale writer is caught
by the board's `version`, which the client echoes back and which is bumped on
every accepted write.
"""
from __future__ import annotations

import json
import re
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from . import db

# Caps. Every one of these is enforced by rejecting the whole request, never by
# quietly truncating: a user who pasted a 90-character board name should be told
# it is too long, not shown a name they did not choose.
MAX_BOARD_NAME = 60
MAX_CATEGORY_LABEL = 40
MAX_RANK_PRIORITY = 1000
MAX_BOARDS_PER_USER = 50
MAX_BOARDS_PER_YEAR = 20
MAX_CATEGORIES_PER_BOARD = 30
# Far above the 100-item export ceiling on purpose: a board is a working set to
# curate down from, not just the finished list. This is also the number the
# pool's pagination and the poster warming are sized against.
MAX_ITEMS_PER_BOARD = 1000
MAX_UID_LENGTH = 64

MEDIA_VALUES = frozenset({"show", "movie"})
MEDIA_SCOPES = frozenset({"show", "movie", "mixed"})
# The identity waterfall, in preference order. A row's match_source is whichever
# of these was the first shared id available when the title was resolved.
MATCH_SOURCES = ("tmdb", "tvdb", "imdb", "mal")
ADDED_FROM_VALUES = frozenset({"manual", "tracker", "ratings"})

_COLOUR = re.compile(r"^#[0-9A-Fa-f]{6}$")
# A uid is generated by the client and then used as a database key and an HTML
# id, so it is held to an unambiguous alphabet rather than trusted.
_UID = re.compile(r"^[A-Za-z0-9_-]{1,%d}$" % MAX_UID_LENGTH)

# The columns a board row exposes outside this module, in the order the UI reads
# them. Listed once so fetch_boards and fetch_board cannot drift apart.
_BOARD_FIELDS = ("uid", "name", "year", "media_scope", "sort_order",
                 "created_at", "updated_at", "version")


class RankerError(Exception):
    """Base for the refusals this module raises. Each subclass maps to one HTTP
    status in the route layer, which is the only place that knows about HTTP."""


class BoardNotFound(RankerError):
    """No board with that uid belongs to this user.

    Deliberately the same answer for "no such board" and "somebody else's
    board": a caller who can tell those apart can enumerate other people's
    boards by uid, which is exactly the disclosure the uid addressing exists to
    prevent.
    """


class ValidationError(RankerError):
    """A payload broke a cap or a format rule. Nothing was written."""


class VersionConflict(RankerError):
    """The board changed since the client last read it — another tab saved
    first. The caller reloads rather than guessing which write wins."""


@dataclass(frozen=True)
class ItemKey:
    """An item's identity within a board: the same triple as its UNIQUE
    constraint, parsed from the composite key a client sends."""
    media: str
    match_source: str
    match_id: str

    def __str__(self) -> str:
        return f"{self.media}:{self.match_source}:{self.match_id}"


def item_key(media: str, match_source: str, match_id: str) -> str:
    """The string a client uses to name one item on a board."""
    return str(ItemKey(media, match_source, match_id))


def parse_item_key(value: Any) -> ItemKey:
    """Parse a composite item key, raising rather than returning a sentinel a
    caller could forget to check.

    Split at most twice, because an imdb or mal id is opaque to us and may one
    day contain the separator; media and match_source never can, since both come
    from closed sets checked here.
    """
    if not isinstance(value, str):
        raise ValidationError("Item keys must be strings.")
    parts = value.split(":", 2)
    if len(parts) != 3:
        raise ValidationError(f"Malformed item key: {value!r}.")
    media, match_source, match_id = parts
    if media not in MEDIA_VALUES:
        raise ValidationError(f"Unknown media type {media!r}.")
    if match_source not in MATCH_SOURCES:
        raise ValidationError(f"Unknown match source {match_source!r}.")
    if not match_id:
        raise ValidationError("An item key needs a match id.")
    return ItemKey(media, match_source, match_id)


# ---------------------------------------------------------------------------
# validation
# ---------------------------------------------------------------------------

def _uid(value: Any, what: str) -> str:
    if not isinstance(value, str) or not _UID.match(value):
        raise ValidationError(
            f"A {what} id must be 1-{MAX_UID_LENGTH} characters of letters, "
            "digits, hyphen or underscore."
        )
    return value


def _name(value: Any, limit: int, what: str) -> str:
    if value is None:
        return ""
    if not isinstance(value, str):
        raise ValidationError(f"A {what} must be text.")
    text = value.strip()
    if len(text) > limit:
        raise ValidationError(f"A {what} can be at most {limit} characters.")
    return text


def _year(value: Any) -> int | None:
    if value is None or value == "":
        return None
    try:
        year = int(value)
    except (TypeError, ValueError):
        raise ValidationError("Year must be a whole number.") from None
    # Wide enough for anything anyone would group a board by, narrow enough that
    # a stray timestamp pasted into the field is caught here rather than stored.
    if not 1870 <= year <= 2200:
        raise ValidationError("Year must be between 1870 and 2200.")
    return year


def _media_scope(value: Any) -> str:
    if value is None:
        return "mixed"
    if value not in MEDIA_SCOPES:
        raise ValidationError("Media scope must be one of: show, movie, mixed.")
    return str(value)


def _rank_priority(value: Any) -> int:
    try:
        priority = int(value)
    except (TypeError, ValueError):
        raise ValidationError("Rank priority must be a whole number.") from None
    if not 0 <= priority <= MAX_RANK_PRIORITY:
        raise ValidationError(f"Rank priority must be between 0 and {MAX_RANK_PRIORITY}.")
    return priority


def _colour(value: Any) -> str | None:
    if value is None or value == "":
        return None
    if not isinstance(value, str) or not _COLOUR.match(value):
        raise ValidationError("Colour must look like #RRGGBB.")
    return value.upper()


# ---------------------------------------------------------------------------
# ownership resolution — every public function starts here
# ---------------------------------------------------------------------------

def _resolve_board(conn: db.Connection, user_id: int, board_uid: str):
    """The caller's board row, or BoardNotFound. The ONLY way an integer board
    id is ever obtained."""
    row = conn.execute(
        "SELECT * FROM tier_boards WHERE user_id = ? AND uid = ?",
        (user_id, _uid(board_uid, "board")),
    ).fetchone()
    if row is None:
        raise BoardNotFound(f"No board {board_uid!r}.")
    return row


def _category_ids(conn: db.Connection, board_id: int) -> dict[str, int]:
    """uid -> id for every category on a board that has already been resolved to
    its owner, so these ids are owned by construction."""
    return {
        str(row["uid"]): int(row["id"])
        for row in conn.execute(
            "SELECT id, uid FROM tier_categories WHERE board_id = ?", (board_id,)
        )
    }


def _item_ids(conn: db.Connection, board_id: int) -> dict[str, int]:
    """Composite item key -> id, for one already-owned board."""
    return {
        item_key(row["media"], row["match_source"], row["match_id"]): int(row["id"])
        for row in conn.execute(
            "SELECT id, media, match_source, match_id FROM tier_items WHERE board_id = ?",
            (board_id,),
        )
    }


def _board_dict(row) -> dict[str, Any]:
    return {field: row[field] for field in _BOARD_FIELDS}


def _item_dict(row) -> dict[str, Any]:
    try:
        ids = json.loads(row["ids_json"])
    except ValueError:
        # A malformed map is provenance we can no longer read; it must not take
        # the board down with it, and the row's own match_source/match_id are
        # what the feature actually ranks by.
        ids = {}
    return {
        "key": item_key(row["media"], row["match_source"], row["match_id"]),
        "media": row["media"],
        "match_source": row["match_source"],
        "match_id": row["match_id"],
        "tmdb": row["tmdb"],
        "ids": ids if isinstance(ids, dict) else {},
        "title": row["title"],
        "year": row["year"],
        "network": row["network"],
        "season_count": row["season_count"],
        "episode_count": row["episode_count"],
        "runtime": row["runtime"],
        "user_rating": row["user_rating"],
        "added_from": row["added_from"],
        "rank_in_category": row["rank_in_category"],
    }


# ---------------------------------------------------------------------------
# boards
# ---------------------------------------------------------------------------

async def fetch_boards(user_id: int) -> list[dict[str, Any]]:
    """Every board this user owns, with its item count, newest grouping first.

    The count comes from one grouped join rather than a query per board — a user
    at the 50-board cap would otherwise cost 51 round trips to draw a switcher.
    """
    rows = await db.fetch_all(
        "SELECT b.*, COUNT(i.id) AS item_count "
        "  FROM tier_boards b LEFT JOIN tier_items i ON i.board_id = b.id "
        " WHERE b.user_id = ? "
        " GROUP BY b.id "
        " ORDER BY b.year IS NULL, b.year DESC, b.sort_order, b.id",
        (user_id,),
    )
    return [{**_board_dict(row), "item_count": int(row["item_count"])} for row in rows]


async def create_board(
    user_id: int,
    *,
    uid: str,
    name: str = "",
    year: int | None = None,
    media_scope: str = "mixed",
) -> dict[str, Any]:
    """Create an empty board. Raises ValidationError when a cap is reached."""
    board_uid = _uid(uid, "board")
    board_name = _name(name, MAX_BOARD_NAME, "board name")
    board_year = _year(year)
    scope = _media_scope(media_scope)
    ts = db.now()

    def _work(conn: db.Connection) -> dict[str, Any]:
        _check_board_caps(conn, user_id, board_year)
        if conn.execute(
            "SELECT 1 FROM tier_boards WHERE user_id = ? AND uid = ?", (user_id, board_uid)
        ).fetchone():
            raise ValidationError("That board already exists.")
        # Appended after whatever the user already has, so a new board does not
        # displace the ordering they arranged.
        next_order = int(conn.execute(
            "SELECT COALESCE(MAX(sort_order), -1) + 1 FROM tier_boards WHERE user_id = ?",
            (user_id,),
        ).fetchone()[0])
        conn.execute(
            "INSERT INTO tier_boards (user_id, uid, name, year, media_scope, sort_order, "
            "created_at, updated_at, version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0)",
            (user_id, board_uid, board_name, board_year, scope, next_order, ts, ts),
        )
        return _board_dict(_resolve_board(conn, user_id, board_uid))

    return await db.transaction(_work)


def _check_board_caps(conn: db.Connection, user_id: int, year: int | None) -> None:
    """Both board caps, checked inside the write transaction so two concurrent
    creates cannot both find room for the same last slot."""
    total = int(conn.execute(
        "SELECT COUNT(*) FROM tier_boards WHERE user_id = ?", (user_id,)
    ).fetchone()[0])
    if total >= MAX_BOARDS_PER_USER:
        raise ValidationError(f"You can have at most {MAX_BOARDS_PER_USER} boards.")
    if year is not None:
        in_year = int(conn.execute(
            "SELECT COUNT(*) FROM tier_boards WHERE user_id = ? AND year = ?", (user_id, year)
        ).fetchone()[0])
        if in_year >= MAX_BOARDS_PER_YEAR:
            raise ValidationError(
                f"You can have at most {MAX_BOARDS_PER_YEAR} boards for {year}."
            )


async def update_board(
    user_id: int,
    board_uid: str,
    *,
    name: Any = None,
    year: Any = None,
    media_scope: Any = None,
) -> dict[str, Any]:
    """Rename a board and/or change its year or media scope.

    Each field is applied only when it was supplied, so a rename does not have to
    restate the year to avoid clearing it. Clearing the year is expressed by
    passing the empty string, which _year() reads as None — `None` here means
    "not part of this request" and cannot also mean "set it to nothing".
    """
    updates: dict[str, Any] = {}
    if name is not None:
        updates["name"] = _name(name, MAX_BOARD_NAME, "board name")
    if year is not None:
        updates["year"] = _year(year)
    if media_scope is not None:
        updates["media_scope"] = _media_scope(media_scope)

    def _work(conn: db.Connection) -> dict[str, Any]:
        board = _resolve_board(conn, user_id, board_uid)
        if updates:
            if "year" in updates and updates["year"] != board["year"]:
                _check_year_cap(conn, user_id, updates["year"])
            assignments = ", ".join(f"{column} = ?" for column in updates)
            conn.execute(
                f"UPDATE tier_boards SET {assignments}, updated_at = ? "
                " WHERE id = ? AND user_id = ?",
                (*updates.values(), db.now(), int(board["id"]), user_id),
            )
        return _board_dict(_resolve_board(conn, user_id, board_uid))

    return await db.transaction(_work)


def _check_year_cap(conn: db.Connection, user_id: int, year: int | None) -> None:
    """The per-year cap on its own, for a board moving INTO a year rather than
    being created in one."""
    if year is None:
        return
    in_year = int(conn.execute(
        "SELECT COUNT(*) FROM tier_boards WHERE user_id = ? AND year = ?", (user_id, year)
    ).fetchone()[0])
    if in_year >= MAX_BOARDS_PER_YEAR:
        raise ValidationError(f"You can have at most {MAX_BOARDS_PER_YEAR} boards for {year}.")


async def delete_board(user_id: int, board_uid: str) -> None:
    """Delete a board and, by cascade, its categories and items."""
    def _work(conn: db.Connection) -> None:
        board = _resolve_board(conn, user_id, board_uid)
        conn.execute(
            "DELETE FROM tier_boards WHERE id = ? AND user_id = ?", (int(board["id"]), user_id)
        )

    await db.transaction(_work)


async def clone_board(
    user_id: int, board_uid: str, *, uid: str, name: str = "",
) -> dict[str, Any]:
    """Copy a board, its tiers and everything in them onto a new uid.

    The copy is made entirely with INSERT...SELECT against ids that were resolved
    from the source board, so nothing crosses out of the caller's own data even
    if the source somehow held a stray reference.
    """
    new_uid = _uid(uid, "board")
    ts = db.now()

    def _work(conn: db.Connection) -> dict[str, Any]:
        source = _resolve_board(conn, user_id, board_uid)
        source_id = int(source["id"])
        new_name = _name(name, MAX_BOARD_NAME, "board name") or _clone_name(source["name"])
        _check_board_caps(conn, user_id, source["year"])
        if conn.execute(
            "SELECT 1 FROM tier_boards WHERE user_id = ? AND uid = ?", (user_id, new_uid)
        ).fetchone():
            raise ValidationError("That board already exists.")
        next_order = int(conn.execute(
            "SELECT COALESCE(MAX(sort_order), -1) + 1 FROM tier_boards WHERE user_id = ?",
            (user_id,),
        ).fetchone()[0])
        cur = conn.execute(
            "INSERT INTO tier_boards (user_id, uid, name, year, media_scope, sort_order, "
            "created_at, updated_at, version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0)",
            (user_id, new_uid, new_name, source["year"], source["media_scope"],
             next_order, ts, ts),
        )
        new_id = int(cur.lastrowid)
        conn.execute(
            "INSERT INTO tier_categories (board_id, uid, label, rank_priority, is_isolated, "
            "sort_order, colour, created_at) "
            "SELECT ?, uid, label, rank_priority, is_isolated, sort_order, colour, ? "
            "  FROM tier_categories WHERE board_id = ?",
            (new_id, ts, source_id),
        )
        # Categories are matched back up by uid, which is unique per board and
        # was copied verbatim — so an item lands in the copy of the tier it was
        # in, with no id map to build in Python.
        conn.execute(
            "INSERT INTO tier_items (board_id, category_id, media, match_source, match_id, "
            "tmdb, ids_json, title, year, network, season_count, episode_count, runtime, "
            "user_rating, added_from, rank_in_category, created_at) "
            "SELECT ?, (SELECT c.id FROM tier_categories c "
            "             JOIN tier_categories o ON o.uid = c.uid "
            "            WHERE c.board_id = ? AND o.id = i.category_id), "
            "       i.media, i.match_source, i.match_id, i.tmdb, i.ids_json, i.title, i.year, "
            "       i.network, i.season_count, i.episode_count, i.runtime, i.user_rating, "
            "       i.added_from, i.rank_in_category, ? "
            "  FROM tier_items i WHERE i.board_id = ?",
            (new_id, new_id, ts, source_id),
        )
        return _board_dict(_resolve_board(conn, user_id, new_uid))

    return await db.transaction(_work)


def _clone_name(name: Any) -> str:
    """"Top 2026" -> "Top 2026 (copy)", trimmed back under the cap if the
    original was already near it."""
    base = (str(name) if name else "").strip() or "Untitled"
    suffix = " (copy)"
    return base[:MAX_BOARD_NAME - len(suffix)] + suffix


async def fetch_board(user_id: int, board_uid: str) -> dict[str, Any]:
    """One board with its categories, its tiered items and its pool.

    TWO queries for the contents regardless of how many tiers the board has —
    one for the categories, one for every item — grouped in Python afterwards.
    A query per category would make a 30-tier board 31 round trips to draw.
    """
    return await db.run(lambda conn: read_board(conn, user_id, board_uid))


def read_board(conn: db.Connection, user_id: int, board_uid: str) -> dict[str, Any]:
    """SYNCHRONOUS. The body of fetch_board, taking a connection so a caller
    already inside a transaction — a restore, say — can compose it rather than
    opening a second one."""
    board = _resolve_board(conn, user_id, board_uid)
    board_id = int(board["id"])
    categories = conn.execute(
        "SELECT * FROM tier_categories WHERE board_id = ? ORDER BY sort_order, id",
        (board_id,),
    ).fetchall()
    items = conn.execute(
        "SELECT * FROM tier_items WHERE board_id = ? ORDER BY rank_in_category, id",
        (board_id,),
    ).fetchall()

    by_category: dict[int, list[dict[str, Any]]] = {}
    pool: list[dict[str, Any]] = []
    for row in items:
        target = pool if row["category_id"] is None else \
            by_category.setdefault(int(row["category_id"]), [])
        target.append(_item_dict(row))

    return {
        **_board_dict(board),
        "categories": [
            {
                "uid": row["uid"],
                "label": row["label"],
                "rank_priority": row["rank_priority"],
                "is_isolated": bool(row["is_isolated"]),
                "sort_order": row["sort_order"],
                "colour": row["colour"],
                "items": by_category.get(int(row["id"]), []),
            }
            for row in categories
        ],
        "pool": pool,
    }


# ---------------------------------------------------------------------------
# items
# ---------------------------------------------------------------------------

async def add_titles(
    user_id: int,
    board_uid: str,
    refs: list[Mapping[str, Any]],
    *,
    added_from: str = "manual",
) -> int:
    """Add titles to a board's pool, returning how many were actually new.

    Idempotent by way of the board's UNIQUE constraint: re-adding a title that
    is already on the board — in the pool OR already tiered — does nothing,
    rather than duplicating it or dragging it back out of the tier it is in.

    `refs` are mappings carrying the item fields; the provider adapters that
    produce them convert their own value type into this shape, so nothing in
    this module knows which service a title came from.
    """
    if added_from not in ADDED_FROM_VALUES:
        raise ValidationError(f"Unknown source {added_from!r}.")
    rows = [_normalize_ref(ref) for ref in refs]
    ts = db.now()

    def _work(conn: db.Connection) -> int:
        board = _resolve_board(conn, user_id, board_uid)
        board_id = int(board["id"])
        existing = int(conn.execute(
            "SELECT COUNT(*) FROM tier_items WHERE board_id = ?", (board_id,)
        ).fetchone()[0])
        # Counted against the cap before inserting rather than after, so a
        # request that would overflow is refused whole rather than half applied.
        keys = {item_key(r["media"], r["match_source"], r["match_id"]) for r in rows}
        known = set(_item_ids(conn, board_id))
        if existing + len(keys - known) > MAX_ITEMS_PER_BOARD:
            raise ValidationError(f"A board holds at most {MAX_ITEMS_PER_BOARD} titles.")
        added = sum(_insert_item(conn, board_id, row, added_from, ts) for row in rows)
        if added:
            _touch(conn, board_id, user_id, ts)
        return added

    return await db.transaction(_work)


def _insert_item(conn: db.Connection, board_id: int, row: Mapping[str, Any],
                 added_from: str, ts: int, category_id: int | None = None,
                 rank: int = 0) -> int:
    """Insert one title, or do nothing if the board already holds it. Returns 1
    when a row was actually created.

    The one place a tier_items row is written, so every way a title can arrive —
    a search, an import, a ratings seed — stores exactly the same columns and
    respects the same UNIQUE.
    """
    cur = conn.execute(
        "INSERT INTO tier_items (board_id, category_id, media, match_source, match_id, "
        "tmdb, ids_json, title, year, network, season_count, episode_count, runtime, "
        "user_rating, added_from, rank_in_category, created_at) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) "
        "ON CONFLICT (board_id, media, match_source, match_id) DO NOTHING",
        (board_id, category_id, row["media"], row["match_source"], row["match_id"],
         row["tmdb"], row["ids_json"], row["title"], row["year"], row["network"],
         row["season_count"], row["episode_count"], row["runtime"],
         row["user_rating"], added_from, rank, ts),
    )
    return 1 if cur.rowcount > 0 else 0


def _normalize_ref(ref: Mapping[str, Any]) -> dict[str, Any]:
    """Validate one incoming title into exactly the columns tier_items holds."""
    if not isinstance(ref, Mapping):
        raise ValidationError("Each title must be an object.")
    media = ref.get("media", "show")
    if media not in MEDIA_VALUES:
        raise ValidationError(f"Unknown media type {media!r}.")
    match_source = ref.get("match_source")
    if match_source not in MATCH_SOURCES:
        raise ValidationError(f"Unknown match source {match_source!r}.")
    match_id = str(ref.get("match_id") or "").strip()
    if not match_id:
        raise ValidationError("A title needs a match id.")
    ids = ref.get("ids") or {}
    if not isinstance(ids, Mapping):
        raise ValidationError("A title's ids must be an object.")
    return {
        "media": media,
        "match_source": match_source,
        "match_id": match_id,
        "tmdb": _optional_int(ref.get("tmdb")),
        # Unknown keys are omitted rather than stored as nulls, so the map stays
        # a record of what was actually known about this title.
        "ids_json": json.dumps({k: v for k, v in ids.items() if v not in (None, "")},
                               sort_keys=True),
        "title": _name(ref.get("title"), 300, "title"),
        "year": _optional_int(ref.get("year")),
        "network": _name(ref.get("network"), 120, "network"),
        "season_count": _optional_int(ref.get("season_count")),
        "episode_count": _optional_int(ref.get("episode_count")),
        "runtime": _optional_int(ref.get("runtime")),
        "user_rating": _optional_int(ref.get("user_rating")),
    }


def _optional_int(value: Any) -> int | None:
    if value is None or value == "":
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        raise ValidationError(f"Expected a whole number, got {value!r}.") from None


async def remove_items(user_id: int, board_uid: str, keys: list[Any]) -> int:
    """Delete titles from a board entirely — the only true delete in this
    module. Returns how many rows went.

    Every key is resolved against THIS board before anything is deleted, and one
    unresolvable key rejects the whole request: a partial delete driven by a
    payload we did not fully understand is worse than no delete at all.
    """
    parsed = [parse_item_key(key) for key in keys]

    def _work(conn: db.Connection) -> int:
        board = _resolve_board(conn, user_id, board_uid)
        board_id = int(board["id"])
        known = _item_ids(conn, board_id)
        ids = []
        for key in parsed:
            if str(key) not in known:
                raise ValidationError(f"No title {str(key)!r} on this board.")
            ids.append(known[str(key)])
        removed = 0
        for item_id in ids:
            cur = conn.execute(
                "DELETE FROM tier_items WHERE id = ? AND board_id = ?", (item_id, board_id)
            )
            removed += cur.rowcount
        if removed:
            _touch(conn, board_id, user_id, db.now())
        return removed

    return await db.transaction(_work)


# ---------------------------------------------------------------------------
# categories and layout
# ---------------------------------------------------------------------------

async def delete_category(user_id: int, board_uid: str, category_uid: str) -> int:
    """Delete one tier. Its titles fall back to the board's pool rather than
    being deleted with it — losing a curated list to a mis-click is not an
    acceptable outcome, and it is what makes undo trivial.

    Returns how many titles returned to the pool. The fallback itself is the
    schema's ON DELETE SET NULL; this counts them first so the caller can say so.
    """
    def _work(conn: db.Connection) -> int:
        board = _resolve_board(conn, user_id, board_uid)
        board_id = int(board["id"])
        categories = _category_ids(conn, board_id)
        category_id = categories.get(_uid(category_uid, "category"))
        if category_id is None:
            raise ValidationError(f"No tier {category_uid!r} on this board.")
        returned = int(conn.execute(
            "SELECT COUNT(*) FROM tier_items WHERE category_id = ? AND board_id = ?",
            (category_id, board_id),
        ).fetchone()[0])
        conn.execute(
            "DELETE FROM tier_categories WHERE id = ? AND board_id = ?",
            (category_id, board_id),
        )
        _touch(conn, board_id, user_id, db.now())
        return returned

    return await db.transaction(_work)


async def save_layout(user_id: int, board_uid: str, payload: Mapping[str, Any]) -> dict[str, Any]:
    """Write a whole arrangement — tiers, their order, and which titles sit
    where — in one transaction, and return the board's new version.

    The payload is:
        {"version": int,
         "categories": [{"uid", "label", "rank_priority", "is_isolated",
                         "colour", "items": [item key, ...]}, ...],
         "pool": [item key, ...]}

    Rules that make this safe to call from two tabs:
      - `version` must match the stored one or nothing is written (VersionConflict).
      - Every category uid currently on the board must appear in `categories`;
        a uid that does not exist yet creates a tier. A client holding the
        matching version by definition knows the full set, so a missing one means
        the payload was assembled from something other than a current read.
      - Every item key must resolve to a title on THIS board. One that does not
        rejects the whole payload rather than writing the part we understood.
      - Titles named nowhere in the payload are left exactly where they are, so
        a save cannot silently empty a tier it never mentioned.
      - sort_order and rank_in_category are assigned by position here and never
        taken from the client, so the stored ordering is always a dense 0..N-1.
    """
    if not isinstance(payload, Mapping):
        raise ValidationError("Expected a layout object.")
    version = payload.get("version")
    if not isinstance(version, int) or isinstance(version, bool) or version < 0:
        raise ValidationError("A layout save must carry the board version it was built from.")
    categories = payload.get("categories") or []
    if not isinstance(categories, list):
        raise ValidationError("`categories` must be a list.")
    if len(categories) > MAX_CATEGORIES_PER_BOARD:
        raise ValidationError(f"A board holds at most {MAX_CATEGORIES_PER_BOARD} tiers.")
    pool = payload.get("pool") or []
    if not isinstance(pool, list):
        raise ValidationError("`pool` must be a list.")

    wanted = [_normalize_category(entry) for entry in categories]
    if len({entry["uid"] for entry in wanted}) != len(wanted):
        raise ValidationError("Two tiers cannot share an id.")
    pool_keys = [parse_item_key(key) for key in pool]
    ts = db.now()

    def _work(conn: db.Connection) -> dict[str, Any]:
        board = _resolve_board(conn, user_id, board_uid)
        board_id = int(board["id"])
        if int(board["version"]) != version:
            raise VersionConflict(
                "This board changed in another tab. Reload it and try again."
            )

        existing = _category_ids(conn, board_id)
        supplied = {entry["uid"] for entry in wanted}
        if missing := set(existing) - supplied:
            raise ValidationError(
                f"The layout is missing {len(missing)} tier(s) that are on this board."
            )

        known_items = _item_ids(conn, board_id)
        # Resolved for the WHOLE payload before a single write, so an unknown key
        # in the last tier refuses the first tier too.
        placements: list[tuple[int, str, int]] = []
        seen: set[str] = set()
        for entry in wanted:
            for rank, key in enumerate(entry["items"]):
                name = str(key)
                if name not in known_items:
                    raise ValidationError(f"No title {name!r} on this board.")
                if name in seen:
                    raise ValidationError(f"{name!r} appears twice in this layout.")
                seen.add(name)
                placements.append((known_items[name], entry["uid"], rank))
        for key in pool_keys:
            name = str(key)
            if name not in known_items:
                raise ValidationError(f"No title {name!r} on this board.")
            if name in seen:
                raise ValidationError(f"{name!r} appears twice in this layout.")
            seen.add(name)

        category_ids = dict(existing)
        for order, entry in enumerate(wanted):
            category_id = existing.get(entry["uid"])
            if category_id is None:
                cur = conn.execute(
                    "INSERT INTO tier_categories (board_id, uid, label, rank_priority, "
                    "is_isolated, sort_order, colour, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    (board_id, entry["uid"], entry["label"], entry["rank_priority"],
                     int(entry["is_isolated"]), order, entry["colour"], ts),
                )
                category_ids[entry["uid"]] = int(cur.lastrowid)
            else:
                conn.execute(
                    "UPDATE tier_categories SET label = ?, rank_priority = ?, is_isolated = ?, "
                    "sort_order = ?, colour = ? WHERE id = ? AND board_id = ?",
                    (entry["label"], entry["rank_priority"], int(entry["is_isolated"]),
                     order, entry["colour"], category_id, board_id),
                )

        for item_id, category_uid, rank in placements:
            conn.execute(
                "UPDATE tier_items SET category_id = ?, rank_in_category = ? "
                " WHERE id = ? AND board_id = ?",
                (category_ids[category_uid], rank, item_id, board_id),
            )
        for key in pool_keys:
            conn.execute(
                "UPDATE tier_items SET category_id = NULL, rank_in_category = 0 "
                " WHERE id = ? AND board_id = ?",
                (known_items[str(key)], board_id),
            )

        new_version = _touch(conn, board_id, user_id, ts)
        return {"version": new_version}

    return await db.transaction(_work)


def _normalize_category(entry: Any) -> dict[str, Any]:
    if not isinstance(entry, Mapping):
        raise ValidationError("Each tier must be an object.")
    items = entry.get("items") or []
    if not isinstance(items, list):
        raise ValidationError("A tier's `items` must be a list.")
    return {
        "uid": _uid(entry.get("uid"), "tier"),
        "label": _name(entry.get("label"), MAX_CATEGORY_LABEL, "tier label"),
        "rank_priority": _rank_priority(entry.get("rank_priority", 0)),
        "is_isolated": bool(entry.get("is_isolated")),
        "colour": _colour(entry.get("colour")),
        "items": [parse_item_key(key) for key in items],
    }


# ---------------------------------------------------------------------------
# the tier template and the ratings seed
# ---------------------------------------------------------------------------
# One S/A/B/C/D/F set, defined once. The seed creates whichever of these it
# needs, and the UI's "apply template" offers the same six — two spellings of
# the same ladder would put a board in a state where a re-seed created
# duplicates of tiers the user already had.
#
# The uids are FIXED rather than generated, which is what makes "create the ones
# that are missing" work: a second seed finds the tier it made the first time
# instead of adding another beside it. Priorities descend in tens so a user can
# slot something between two of them without renumbering.
TIER_TEMPLATE: tuple[dict[str, Any], ...] = (
    {"uid": "tier-s", "label": "S", "rank_priority": 60, "colour": "#FF7F7F"},
    {"uid": "tier-a", "label": "A", "rank_priority": 50, "colour": "#FFBF7F"},
    {"uid": "tier-b", "label": "B", "rank_priority": 40, "colour": "#FFDF7F"},
    {"uid": "tier-c", "label": "C", "rank_priority": 30, "colour": "#BFEF7F"},
    {"uid": "tier-d", "label": "D", "rank_priority": 20, "colour": "#7FC7FF"},
    {"uid": "tier-f", "label": "F", "rank_priority": 10, "colour": "#B0B4BA"},
)
_TEMPLATE_BY_UID = {entry["uid"]: entry for entry in TIER_TEMPLATE}

# A 1-10 score onto that ladder. The top three scores each get their own tier
# because that is where a person's opinion is most differentiated; everything at
# 5 or below lands together, because "I did not like it" is one verdict however
# it was spelled.
_TIER_FOR_RATING = {10: "tier-s", 9: "tier-a", 8: "tier-b", 7: "tier-c", 6: "tier-d"}
_LOWEST_TIER = "tier-f"


def tier_for_rating(rating: int) -> str:
    """Which template tier a score seeds into."""
    return _TIER_FOR_RATING.get(int(rating), _LOWEST_TIER)


async def seed_ratings(
    user_id: int, board_uid: str, entries: list[Mapping[str, Any]], *, commit: bool = False,
) -> dict[str, Any]:
    """Arrange rated titles into the template tiers, or report what that would
    do when `commit` is false.

    A SEED, NOT A SYNC, and the difference is the whole design:
      - A title the user has already placed is never moved. Their arrangement is
        the artifact; the scores are only a starting point.
      - Titles the board does not hold yet are added with their score, then
        placed. A title that arrives with a rating and no tier would leave the
        user to do by hand the exact work they asked for.
      - Nothing here runs on a schedule or repeats itself. Seeding a board twice
        does nothing the second time beyond whatever was rated in between.

    Titles outside the board's media scope are skipped rather than refused: a
    movies board seeded from a mixed ratings list should get the movies, not an
    error about the shows.

    `entries` carry the tier_items fields plus `user_rating`. Returns the counts
    a preview shows, and — when committed — the board's new version.
    """
    rated = [(_normalize_ref(entry), _rating(entry.get("user_rating"))) for entry in entries]

    def _work(conn: db.Connection) -> dict[str, Any]:
        board = _resolve_board(conn, user_id, board_uid)
        board_id = int(board["id"])
        scope = board["media_scope"]
        in_scope = [(row, score) for row, score in rated
                    if scope == "mixed" or row["media"] == scope]

        placements = _item_placements(conn, board_id)
        categories = _category_ids(conn, board_id)
        # Highest score first so the tiers fill in the order somebody would have
        # dragged them, and so a truncated run keeps the titles that matter most.
        ordered = sorted(in_scope, key=lambda pair: (-pair[1], pair[0]["title"]))

        new_items: list[tuple[dict[str, Any], int, str]] = []   # row, score, tier uid
        moves: list[tuple[int, str]] = []                       # item id, tier uid
        already_placed = 0
        seen: set[str] = set()
        for row, score in ordered:
            key = item_key(row["media"], row["match_source"], row["match_id"])
            if key in seen:
                # The same title twice in one payload — a show rated under two
                # ids, say. The first (highest) score has already claimed it, and
                # counting the second would report an insert the UNIQUE will drop.
                continue
            seen.add(key)
            tier_uid = tier_for_rating(score)
            existing = placements.get(key)
            if existing is None:
                new_items.append((row, score, tier_uid))
            elif existing[1] is not None:
                already_placed += 1
            else:
                moves.append((existing[0], tier_uid))

        wanted_tiers = {uid for _, _, uid in new_items} | {uid for _, uid in moves}
        missing = [uid for entry in TIER_TEMPLATE
                   if (uid := entry["uid"]) in wanted_tiers and uid not in categories]
        if len(categories) + len(missing) > MAX_CATEGORIES_PER_BOARD:
            raise ValidationError(f"A board holds at most {MAX_CATEGORIES_PER_BOARD} tiers.")
        held = int(conn.execute(
            "SELECT COUNT(*) FROM tier_items WHERE board_id = ?", (board_id,)
        ).fetchone()[0])
        if held + len(new_items) > MAX_ITEMS_PER_BOARD:
            raise ValidationError(f"A board holds at most {MAX_ITEMS_PER_BOARD} titles.")

        summary = {
            "tiers_created": len(missing),
            "titles_added": len(new_items),
            "titles_placed": len(new_items) + len(moves),
            "already_placed": already_placed,
            "out_of_scope": len(rated) - len(in_scope),
            "version": int(board["version"]),
        }
        if not commit:
            return summary

        ts = db.now()
        next_order = int(conn.execute(
            "SELECT COALESCE(MAX(sort_order), -1) + 1 FROM tier_categories WHERE board_id = ?",
            (board_id,),
        ).fetchone()[0])
        for offset, uid in enumerate(missing):
            template = _TEMPLATE_BY_UID[uid]
            cur = conn.execute(
                "INSERT INTO tier_categories (board_id, uid, label, rank_priority, is_isolated, "
                "sort_order, colour, created_at) VALUES (?, ?, ?, ?, 0, ?, ?, ?)",
                (board_id, uid, template["label"], template["rank_priority"],
                 next_order + offset, template["colour"], ts),
            )
            categories[uid] = int(cur.lastrowid)

        # Appended AFTER whatever each tier already holds, so a seed onto a board
        # somebody has started arranging never reshuffles their existing order.
        ranks = _next_ranks(conn, board_id, categories.values())
        for row, score, uid in new_items:
            category_id = categories[uid]
            _insert_item(conn, board_id, row, "ratings", ts,
                         category_id=category_id, rank=ranks[category_id])
            ranks[category_id] += 1
        for item_id, uid in moves:
            category_id = categories[uid]
            conn.execute(
                "UPDATE tier_items SET category_id = ?, rank_in_category = ? "
                " WHERE id = ? AND board_id = ?",
                (category_id, ranks[category_id], item_id, board_id),
            )
            ranks[category_id] += 1

        summary["version"] = _touch(conn, board_id, user_id, ts)
        return summary

    return await (db.transaction(_work) if commit else db.run(_work))


def _rating(value: Any) -> int:
    score = _optional_int(value)
    if score is None or not 1 <= score <= 10:
        raise ValidationError("A rating must be a whole number from 1 to 10.")
    return score


def _item_placements(conn: db.Connection, board_id: int) -> dict[str, tuple[int, int | None]]:
    """Composite item key -> (id, category_id), for one already-owned board. The
    category is what tells an unplaced title apart from one the user has already
    put somewhere."""
    return {
        item_key(row["media"], row["match_source"], row["match_id"]):
            (int(row["id"]), row["category_id"])
        for row in conn.execute(
            "SELECT id, category_id, media, match_source, match_id FROM tier_items "
            " WHERE board_id = ?", (board_id,),
        )
    }


def _next_ranks(conn: db.Connection, board_id: int, category_ids) -> dict[int, int]:
    """The rank an appended title takes in each tier: one past whatever is
    already there. Read once for the whole seed rather than per title."""
    ranks = {int(cid): 0 for cid in category_ids}
    for row in conn.execute(
        "SELECT category_id, MAX(rank_in_category) + 1 AS next FROM tier_items "
        " WHERE board_id = ? AND category_id IS NOT NULL GROUP BY category_id",
        (board_id,),
    ):
        ranks[int(row["category_id"])] = int(row["next"])
    return ranks


# ---------------------------------------------------------------------------
# backup and restore
# ---------------------------------------------------------------------------
# EVERYTHING IS KEYED BY uid, NEVER BY INTEGER id. A backup's whole purpose is to
# be restorable somewhere else — a rebuilt database, a second instance, an
# account that was deleted and remade — and in any of those the autoincrement ids
# that were current when the file was written point at unrelated rows or at
# nothing at all. Boards and categories carry their uid; an item names its
# category by that uid, and items are nested inside their board so a uid only has
# to be unique where it actually is (per board).
#
# NOT IN THE DOCUMENT, deliberately: `show_posters` (shared, rebuildable, and
# nobody's personal data), and avatars and saved images (binary, large, and not
# something a JSON document should carry). The UI says so where it offers this.

# Bump only on an incompatible change to the shape below. A restore refuses a
# version it does not understand rather than guessing at the layout.
EXPORT_SCHEMA = 1
SUPPORTED_EXPORT_SCHEMAS = (1,)

# The board columns a backup carries. `version` is not among them: it counts
# saves against THIS database's copy of the board, so carrying it across would
# tell a client to expect a history the restored row does not have.
_BACKUP_BOARD_FIELDS = ("uid", "name", "year", "media_scope", "sort_order",
                        "created_at", "updated_at")
_BACKUP_CATEGORY_FIELDS = ("uid", "label", "rank_priority", "is_isolated",
                           "sort_order", "colour", "created_at")
_BACKUP_ITEM_FIELDS = ("media", "match_source", "match_id", "tmdb", "ids_json",
                       "title", "year", "network", "season_count", "episode_count",
                       "runtime", "user_rating", "added_from", "rank_in_category",
                       "created_at")


async def export_user_data(user_id: int) -> dict[str, Any]:
    """This user's every board, tier and title as one JSON-able document.

    Three queries regardless of how many boards there are — one per table,
    grouped in Python — rather than a walk that costs a query per board.
    """
    def _work(conn: db.Connection) -> dict[str, Any]:
        boards = conn.execute(
            "SELECT * FROM tier_boards WHERE user_id = ? ORDER BY sort_order, id",
            (user_id,),
        ).fetchall()
        categories: dict[int, list[dict[str, Any]]] = {}
        category_uids: dict[int, str] = {}
        for row in conn.execute(
            "SELECT c.* FROM tier_categories c JOIN tier_boards b ON b.id = c.board_id "
            " WHERE b.user_id = ? ORDER BY c.sort_order, c.id",
            (user_id,),
        ):
            categories.setdefault(int(row["board_id"]), []).append(
                {field: row[field] for field in _BACKUP_CATEGORY_FIELDS}
            )
            category_uids[int(row["id"])] = str(row["uid"])
        items: dict[int, list[dict[str, Any]]] = {}
        for row in conn.execute(
            "SELECT i.* FROM tier_items i JOIN tier_boards b ON b.id = i.board_id "
            " WHERE b.user_id = ? ORDER BY i.rank_in_category, i.id",
            (user_id,),
        ):
            entry = {field: row[field] for field in _BACKUP_ITEM_FIELDS}
            # NULL category means the board's pool, and it stays NULL through the
            # round trip: a pool title is unranked work in progress, not a title
            # whose tier went missing.
            entry["category_uid"] = (
                None if row["category_id"] is None
                else category_uids.get(int(row["category_id"]))
            )
            items.setdefault(int(row["board_id"]), []).append(entry)

        return {
            "schema": EXPORT_SCHEMA,
            "exported_at": db.now(),
            "boards": [
                {
                    **{field: row[field] for field in _BACKUP_BOARD_FIELDS},
                    "categories": categories.get(int(row["id"]), []),
                    "items": items.get(int(row["id"]), []),
                }
                for row in boards
            ],
        }

    return await db.run(_work)


async def restore_user_data(user_id: int, doc: Any) -> int:
    """Replace this user's boards with the document's, in one transaction, and
    return how many boards were written.

    REPLACE, not merge: merging would need a conflict rule for every field and
    for every arrangement, and the thing being restored is precisely an
    arrangement. The user comes from the session — a `user_id` anywhere in the
    file is ignored — so a document can never write into somebody else's account.

    The whole document is validated before a single row is deleted, so a file
    that turns out to be malformed halfway through leaves the boards that are
    already here untouched.
    """
    boards = _validate_backup(doc)
    ts = db.now()

    def _work(conn: db.Connection) -> int:
        # The cascade takes the categories and items with it.
        conn.execute("DELETE FROM tier_boards WHERE user_id = ?", (user_id,))
        for order, board in enumerate(boards):
            cur = conn.execute(
                "INSERT INTO tier_boards (user_id, uid, name, year, media_scope, sort_order, "
                "created_at, updated_at, version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0)",
                (user_id, board["uid"], board["name"], board["year"], board["media_scope"],
                 order, board["created_at"] or ts, board["updated_at"] or ts),
            )
            board_id = int(cur.lastrowid)
            category_ids: dict[str, int] = {}
            for position, category in enumerate(board["categories"]):
                cur = conn.execute(
                    "INSERT INTO tier_categories (board_id, uid, label, rank_priority, "
                    "is_isolated, sort_order, colour, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    (board_id, category["uid"], category["label"], category["rank_priority"],
                     int(category["is_isolated"]), position, category["colour"],
                     category["created_at"] or ts),
                )
                category_ids[category["uid"]] = int(cur.lastrowid)
            for item in board["items"]:
                category_uid = item["category_uid"]
                _insert_item(
                    conn, board_id, item["row"], item["added_from"],
                    item["created_at"] or ts,
                    category_id=None if category_uid is None else category_ids[category_uid],
                    rank=item["rank_in_category"],
                )
        return len(boards)

    return await db.transaction(_work)


def _validate_backup(doc: Any) -> list[dict[str, Any]]:
    """Read a backup document into the shape the restore writes, refusing
    anything it cannot fully account for.

    Caps are applied here exactly as they are on a live edit: a document is
    untrusted input like any other, and a file that would build a board no route
    could have built is a file this app should not accept.
    """
    if not isinstance(doc, Mapping):
        raise ValidationError("A backup must be a JSON object.")
    schema = doc.get("schema")
    if schema not in SUPPORTED_EXPORT_SCHEMAS:
        raise ValidationError(f"Unsupported rankings backup version: {schema!r}.")
    raw_boards = doc.get("boards") or []
    if not isinstance(raw_boards, list):
        raise ValidationError("`boards` must be a list.")
    if len(raw_boards) > MAX_BOARDS_PER_USER:
        raise ValidationError(f"A backup can hold at most {MAX_BOARDS_PER_USER} boards.")

    boards = [_validate_backup_board(entry) for entry in raw_boards]
    if len({board["uid"] for board in boards}) != len(boards):
        raise ValidationError("Two boards in this backup share an id.")
    per_year: dict[int, int] = {}
    for board in boards:
        if board["year"] is not None:
            per_year[board["year"]] = per_year.get(board["year"], 0) + 1
            if per_year[board["year"]] > MAX_BOARDS_PER_YEAR:
                raise ValidationError(
                    f"A backup can hold at most {MAX_BOARDS_PER_YEAR} boards for "
                    f"{board['year']}."
                )
    return boards


def _validate_backup_board(entry: Any) -> dict[str, Any]:
    if not isinstance(entry, Mapping):
        raise ValidationError("Each board must be an object.")
    raw_categories = entry.get("categories") or []
    raw_items = entry.get("items") or []
    if not isinstance(raw_categories, list) or not isinstance(raw_items, list):
        raise ValidationError("A board's categories and items must be lists.")
    if len(raw_categories) > MAX_CATEGORIES_PER_BOARD:
        raise ValidationError(f"A board holds at most {MAX_CATEGORIES_PER_BOARD} tiers.")
    if len(raw_items) > MAX_ITEMS_PER_BOARD:
        raise ValidationError(f"A board holds at most {MAX_ITEMS_PER_BOARD} titles.")

    categories = [_validate_backup_category(row) for row in raw_categories]
    uids = {category["uid"] for category in categories}
    if len(uids) != len(categories):
        raise ValidationError("Two tiers on one board share an id.")

    items = [_validate_backup_item(row, uids) for row in raw_items]
    keys = {item_key(item["row"]["media"], item["row"]["match_source"],
                     item["row"]["match_id"]) for item in items}
    if len(keys) != len(items):
        # The UNIQUE would drop the second copy silently, which would restore a
        # board that is quietly smaller than the one that was backed up.
        raise ValidationError("The same title appears twice on one board in this backup.")

    # Ordering is the artifact this feature produces, so it is carried across
    # rather than recomputed — but renumbered densely per tier on the way in, the
    # same normalization a layout save applies, so a hand-edited file cannot
    # introduce gaps or ties the rest of the app does not expect.
    items.sort(key=lambda item: item["rank_in_category"])
    ranks: dict[str | None, int] = {}
    for item in items:
        target = item["category_uid"]
        item["rank_in_category"] = 0 if target is None else ranks.get(target, 0)
        if target is not None:
            ranks[target] = item["rank_in_category"] + 1

    return {
        "uid": _uid(entry.get("uid"), "board"),
        "name": _name(entry.get("name"), MAX_BOARD_NAME, "board name"),
        "year": _year(entry.get("year")),
        "media_scope": _media_scope(entry.get("media_scope")),
        "created_at": _optional_int(entry.get("created_at")),
        "updated_at": _optional_int(entry.get("updated_at")),
        "categories": categories,
        "items": items,
    }


def _validate_backup_category(entry: Any) -> dict[str, Any]:
    if not isinstance(entry, Mapping):
        raise ValidationError("Each tier must be an object.")
    return {
        "uid": _uid(entry.get("uid"), "tier"),
        "label": _name(entry.get("label"), MAX_CATEGORY_LABEL, "tier label"),
        "rank_priority": _rank_priority(entry.get("rank_priority", 0)),
        "is_isolated": bool(entry.get("is_isolated")),
        "colour": _colour(entry.get("colour")),
        "created_at": _optional_int(entry.get("created_at")),
    }


def _validate_backup_item(entry: Any, category_uids: set[str]) -> dict[str, Any]:
    if not isinstance(entry, Mapping):
        raise ValidationError("Each title must be an object.")
    # _normalize_ref reads `ids`, while the export writes the stored `ids_json`
    # verbatim so a round trip is an identity. Parse it back into the map that
    # function expects rather than teaching it a second input shape.
    ref = dict(entry)
    if "ids" not in ref:
        ref["ids"] = _ids_from_json(entry.get("ids_json"))
    row = _normalize_ref(ref)

    category_uid = entry.get("category_uid")
    if category_uid is not None:
        category_uid = _uid(category_uid, "tier")
        if category_uid not in category_uids:
            # Silently pooling it would restore a board whose arrangement is
            # subtly different from the one that was saved, which is the one
            # thing a backup must not do.
            raise ValidationError(
                f"A title in this backup names tier {category_uid!r}, which is not on its board."
            )
    added_from = entry.get("added_from") or "manual"
    if added_from not in ADDED_FROM_VALUES:
        raise ValidationError(f"Unknown source {added_from!r}.")
    rank = _optional_int(entry.get("rank_in_category")) or 0
    if rank < 0:
        raise ValidationError("A rank cannot be negative.")
    return {
        "row": row,
        "category_uid": category_uid,
        "added_from": added_from,
        "rank_in_category": rank,
        "created_at": _optional_int(entry.get("created_at")),
    }


def _ids_from_json(value: Any) -> dict[str, Any]:
    """The provenance map out of a stored `ids_json` string. A map we can no
    longer read is dropped rather than refused: the row's own match_source and
    match_id are what the feature ranks by, and they are validated separately."""
    if not isinstance(value, str) or not value:
        return {}
    try:
        parsed = json.loads(value)
    except ValueError:
        return {}
    return parsed if isinstance(parsed, dict) else {}


def _touch(conn: db.Connection, board_id: int, user_id: int, ts: int) -> int:
    """Stamp a board as changed and bump the version a client echoes back.
    Returns the new version.

    Carries the ownership predicate even though the caller resolved the board
    already: every write in this module does, so no single missed check is enough
    to write across accounts.
    """
    conn.execute(
        "UPDATE tier_boards SET updated_at = ?, version = version + 1 "
        " WHERE id = ? AND user_id = ?",
        (ts, board_id, user_id),
    )
    return int(conn.execute(
        "SELECT version FROM tier_boards WHERE id = ?", (board_id,)
    ).fetchone()[0])
